disabled_rules:
  - identifier_name
  - nesting
  - function_parameter_count
  - static_over_final_class
  - private_over_fileprivate
opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma

included:
  - VIPER_with_Repository/
  - VIPER_with_RepositoryTests/
excluded:
  - VIPER_with_RepositoryUITests/
  - Pods/
  - Products/
  - Frameworks/
  - Carthage/

force_cast: warning

force_try:
  severity: warning

type_body_length:
  - 300
  - 400

file_length:
  warning: 500
  error: 800

large_tuple:
   - 3
   - 4

